### ISSUE TITLE
Jumpcutting 12 hour video "jumpcutter.py in line 108"...

### ISSUE THREAD

**Issue by kubo6472** [carykh/jumpcutter#110]
Hi, 
So I tried this on a 12-hour video, and it failed on audio. It throws me an error saying: 
```
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Python37\lib\site-packages\scipy\io\wavfile.py", line 264, in read
    is_big_endian, mmap)
  File "C:\Python37\lib\site-packages\scipy\io\wavfile.py", line 129, in _read_data_chunk
    data = numpy.frombuffer(fid.read(size), dtype=dtype)
ValueError: buffer size must be a multiple of element size.
```
Here is the full log: https://pastebin.com/5Re462TW. Now, I still have the cmd open and TEMP folder with ALL the 1.8 million frames. I need to edit your code, to just start extracting the audio, and continue. Can somebody help me with that? I started learning python only this year at my school.

**Comment by torsrex** [comment]
May I suggest splitting the video up into 1h cunks, running the script on those 1h chunks and then combining them together again? 

Splitting can be done using: 
```
ffmpeg -i input.mp4 -c copy -map 0 -segment_time 01:00:00 -f segment output%03d.mp4
```
Then run the jumpcutter script on each individual file. Then move the files to a separate folder. Run this
```
(for %i in (*.mp4) do @echo file '%i') > mylist.txt
```
Which will create a list of all the files. You might want to check the mylist.txt file to ensure the order is correct. Then run 
```
ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4
```
to combine the files back together, and you should be good!

**Comment by kubo6472** [comment]
Thanks, going to try in a moment. But forgot to mention that this happened on Windows, so I dunno if the 2nd command will work.

Jakub Doboš, COO
WaMIS Slovakia
90027, Bernolákovo

Sent from Mail for Windows 10

**Comment by kubo6472** [comment]
Thanks, worked out great for the jumpcutter part. Since I was on windows, and knew I had mp4box installed, I merged the files using that (-add and -cat)
So thanks, this is resolved and it can be closed#110

Jakub Doboš, COO
WaMIS Slovakia
90027, Bernolákovo

Sent from Mail for Windows 10

**Comment by kubo6472** [comment]
Okay, this just happened, does that mean, that that part of the video is without audio ?
Traceback (most recent call last):
  File "jumpcutter.py", line 133, in <module>
    maxchunksVolume = float(getMaxVolume(audiochunks))/maxAudioVolume
ZeroDivisionError: float division by zero


Jakub Doboš, COO
WaMIS Slovakia
90027, Bernolákovo

Sent from Mail for Windows 10

**Comment by Lamaun** [comment]
I took the idea @torsrex had and wrote a script for it https://github.com/Lamaun/jumpcutter/blob/master/jumpcutter.sh

**Comment by torsrex** [comment]
I'm not quite sure why you get that error. The script should be able to handle silent files. Perhaps you could, if possible, try to obtain a new copy of the source? Otherwise, re-encoding the source might also work using e.g. handbrake, or ffmpeg.

**Comment by kubo6472** [comment]
Hi, thanks for everything. The combination of re-encoding thru HandBrake, and obtaining a new jumpcutter.py along with all the extensions, pip, and python updates made it eventually working. I am so happy this project has got this active community.


Jakub Doboš, COO
WaMIS Slovakia
90027, Bernolákovo

Sent from Mail for Windows 10
