### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by TheStrangePototo** [carykh/jumpcutter#113]
Sorry if this is too much to ask or the wrong place to ask, but I just want to know if it would be possible to convert into an APK so I can use it on my phone? I'm on a trip right now and don't have access to a computer. If it's not possible, I'll just wait until I get home.

**Comment by Gusted** [comment]
You can try download Qpython and download all pip packages and then try to run the file but, don't know if it's works.

**Comment by ThatOneCalculator** [comment]
Uh no. It needs ffmpeg, and that's not on Android or iPhone

**Comment by TheStrangePototo** [comment]
@ThatOneCalculator Thanks! CaryKH said in the video that he might eventually make an app with hand gestures too, I'll just wait for that. My vacation is almost over, so I can use it on my laptop when I get home.
