### ISSUE TITLE
PIL module

### ISSUE THREAD

**Issue by TheStrangePototo** [carykh/jumpcutter#114]
ModuleNotFoundError: No module named 'PIL'

I know there's already an issue for this, but my problem is that whenever I try to install Pillow, it says 
FileNotFoundError: [Errno 2] No such file or directory: 'src/PIL/_version.py'
I'm new to Python, but I checked the file directories and that file exists.

**Comment by Lamaun** [comment]
Similar to #83 as you pointed out. (Just to possibly save someone from the search)

Please be more specific.
What operating system are you using?
What version of pip and python are you using?
What did you do to reach your current state?

**Comment by TheStrangePototo** [comment]
@Lamaun 
Operating System: Windows 10
Python: 3.7
I don't know how to check the other 2, sorry.

**Comment by Lamaun** [comment]
Did you install pip?
If you want to build from source you should first install pip and than install requirements.txt with pip.

Alternativly this fork seems to have an executable https://github.com/izedout/jumpcutter#executable.
(Try at your own risk)

You could also install docker and use my forks Dockerfile https://github.com/Lamaun/jumpcutter/

**Comment by Lamaun** [comment]
You could also try to follow this https://github.com/kbartek05/jumpcutter/tree/patch-6#windows.

**Comment by TheStrangePototo** [comment]
@Lamaun Thanks for the link to the executable! It'll save me a lot of time since I have Python and the 'PATH' thing set up.

**Comment by TheStrangePototo** [comment]
@Lamaun Thanks for all the help, but I still couldn't get it to work. Luckily, I managed to find a working installer .exe at this link:
https://github.com/will9183/jumpcutter/releases/download/v1.2-beta/jumpcutter-installer.exe

**Comment by TheStrangePototo** [comment]
@Lamaun Ok, so I keep running into errors when I try to use the installer. The program opens fine, when I try to use it, an error comes up. Man, this thing is hard. Do you know where the Discord invite is? Maybe I could get help there.

**Comment by TheStrangePototo** [comment]
@Lamaun Ok, so I keep running into errors when I try to use the installer. The program opens fine, when I try to use it, an error comes up. Man, this thing is hard. Do you know where the Discord invite is? Maybe I could get help there.

**Comment by Lamaun** [comment]
All I found is the subreddit https://www.reddit.com/r/tenwordsofwisdom
Two posts there post discord invites but both expired.

**Comment by TheStrangePototo** [comment]
@Lamaun Thanks! I'll ask for a link on the subreddit.

**Comment by Lamaun** [comment]
Ok but to communicate effectively this should be solved here too.

I actually booted my windows for this and just wrote down what I did to get a running jumpcutter:

1. Download https://www.python.org/ftp/python/3.7.3/python-3.7.3-amd64.exe
2. Execute downloaded File -> Click Install Python
3. Download https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20190612-caabe1b-win64-static.zip
4. Extract downloaded File
5. Download https://github.com/carykh/jumpcutter/archive/master.zip
6. Extract downloaded File
7. Move ffmpeg/bin/ffmpeg.exe to jumpcutter-master/jumpcutter-master folder
8. Open cmd
9. cd Downloads\jumpcutter-master\jumpcutter-master
10. C:\Users\YOUR_USERNAME_HERE\AppData\Local\Programs\Python\Python37\python.exe -m pip install -r requirements.txt
11. C:\Users\YOUR_USERNAME_HERE\AppData\Local\Programs\Python\Python37\python.exe jumpcutter.py --input_file input.mp4

Please try this and if something is unclear to you just ask here.

**Comment by TheStrangePototo** [comment]
@Lamaun Thank you so much! I'll try this and get back to you.

**Comment by TheStrangePototo** [comment]
@Lamaun Okay, I got it to work, but there's a problem. It worked fine on the first video I used it on, but on the other 2 I used it on, the video gets stuck on 1 frame halfway through the video.

**Comment by Lamaun** [comment]
**Please be more specific.**
Can you provide the video in question or can you find other videos it doesn't work with?

**Comment by Lamaun** [comment]
Also you should probably close this issue and open a new one with the new problem

**Comment by TheStrangePototo** [comment]
@Lamaun  k I'll start a new issue.

**Comment by DaRealOctopus** [comment]
can you help me I am stuck at number 10 what will you do there?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus What do you not understand? (Not trying to be mean, be just wanting to know the problem)

**Comment by DaRealOctopus** [comment]
what am I gonna do in number 10?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus you paste it into cmd

**Comment by DaRealOctopus** [comment]
so I paste C:\Users\YOUR_USERNAME_HERE\AppData\Local\Programs\Python\Python37\python.exe -m pip install -r requirements.txt to cmd?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus but you replace YOUR-USERNAME-HERE with the username on your computer

**Comment by DaRealOctopus** [comment]
it says '-m' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TheStrangePototo** [comment]
@DaRealOctopus Ok so instead of YOUR-USERNAME here, you replaced it with whatever username the computer has under C:\Users, right? And you opened cmd as an administrator, right?

**Comment by DaRealOctopus** [comment]
how do I check to see if the cmd is at administrator?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus If you have to check if it is, then you didn't open it as administrator. You have to open cmd by right-clicking on it and clicking "Open as Administrator". The option should have a little yellow and blue shield there

**Comment by DaRealOctopus** [comment]
C:\Users\Benedict Jose\AppData\Local\Programs\Python\Python37-32>-m pip install -r requirements.txt
'-m' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TheStrangePototo** [comment]
@DaRealOctopus there's not supposed to be a ">"

**Comment by DaRealOctopus** [comment]
cd C:\Users\Benedict Jose\AppData\Local\Programs\Python\Python37\python.exe
do I put a cd the front?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus no,
here's what you diddly do. you e done steps 1-7, right? So do this:

1) Right click cmd and open as administrator.

2) type in cd Downloads\jumpcutter-master\jumpcutter-master

And press enter

3) type in C:\Users\Benedict Jose\AppData\Local\Programs\Python\Python37\python.exe -m pip install -r requirements.txt

and press enter

4) type in

C:\Users\Benedict Jose\AppData\Local\Programs\Python\Python37\python.exe jumpcutter.py --input_file input.mp4

Make sure to put the framerate, and replace input.mp4 with whatever video your using

**Comment by DaRealOctopus** [comment]
it says C:\WINDOWS\system32>cd Downloads\jumpcutter-master\jumpcutter-master
The system cannot find the path specified.

**Comment by TheStrangePototo** [comment]
Hmmmmmmmm.

**Comment by DaRealOctopus** [comment]
should I type this instead
cd C:\Jumpcatter\jumpcutter-master?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus I'm really stumped. Maybe you could @ Lamaun? He's the one who figured this out for me and made the steps.

**Comment by DaRealOctopus** [comment]
when will he/she be active?

**Comment by DaRealOctopus** [comment]
Hey @TheStrangePototo I think I've done it

**Comment by DaRealOctopus** [comment]
it now says
Collecting Pillow (from -r requirements.txt (line 1))
is this good?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus YES! You did it! I think it's installing the required repositories right now.

**Comment by DaRealOctopus** [comment]
r u proud of me?

**Comment by DaRealOctopus** [comment]
uh oh
it says in red text
Command "python setup.py egg_info" failed with error code C:\Users\BENEDI~2\AppData\Local\Temp\pip-build-cxhvczq2\scipy

**Comment by TheStrangePototo** [comment]
@DaRealOctopus yeah you're goin ta need Lamaun on this one. just, egg info? Sounds like a meme.

**Comment by DaRealOctopus** [comment]
help mine says

Traceback (most recent call last):
  File "jumpcutter.py", line 2, in <module>
    from PIL import Image
ImportError: cannot import name 'Image'

**Comment by TheStrangePototo** [comment]
@Lamaun @DaRealOctopus needs help

**Comment by DaRealOctopus** [comment]
@Lamaun @Lamaun  @Lamaun

**Comment by DaRealOctopus** [comment]
@Lamaun @Lamaun @Lamaun

**Comment by DaRealOctopus** [comment]
hey @TheStrangePototo did u used 
https://github.com/will9183/jumpcutter/releases/download/v1.2-beta/jumpcutter-installer.exe
?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus I tried but it didn't work. Even after I used this method (which should work for you after Lamaun helps) it didn't work.

**Comment by DaRealOctopus** [comment]
u said

Lamaun Thanks for all the help, but I still couldn't get it to work. Luckily, I managed to find a working installer .exe at this link:
https://github.com/will9183/jumpcutter/releases/download/v1.2-beta/jumpcutter-installer.exe

**Comment by TheStrangePototo** [comment]
@DaRealOctopus yeah, I also said 
"Lamaun Ok, so I keep running into errors when I try to use the installer. The program opens fine, when I try to use it, an error comes up. Man, this thing is hard. Do you know where the Discord invite is? Maybe I could get help there."

**Comment by DaRealOctopus** [comment]
oahhh

**Comment by TheStrangePototo** [comment]
@DaRealOctopus Wait for @Lamaun, he usually answers quickly.

**Comment by DaRealOctopus** [comment]
what are the errors?

**Comment by TheStrangePototo** [comment]
@DaRealOctopus it just didn't work. I think it said it worked, but it didn't

**Comment by DaRealOctopus** [comment]
my error is
Traceback (most recent call last):
  File "jumpcutter.py", line 2, in <module>
    from PIL import Image
ImportError: cannot import name 'Image'

**Comment by Lamaun** [comment]
> @DaRealOctopus Ok so instead of YOUR-USERNAME here, you replaced it with whatever username the computer has under C:\Users, right? And you opened cmd as an administrator, right?

Administrator rights shouldn't be needed for this. (at least if you didn't mess up any permissions on your home folder, so it might help in rare cases)

> it typed C:\WINDOWS\system32>cd Downloads\jumpcutter-master\jumpcutter-master then it says
> The system cannot find the path specified.

Terminals show you your current path. In this case the terminal opened in C:\WINDOWS\system32.
cd is the command to **c**hange **d**irectories. In my tutorial I expected you to already be in your home Folder (C:\Users\Benedict Jose). I will change the original reply to not make this assumption.

Please provide the entire call of the program. Your question should always show exactly what you did.
With the error you provided I think I will also need the output of Step 10.

**Comment by DaRealOctopus** [comment]
hello sorry for not answering you @Lamaun

**Comment by DaRealOctopus** [comment]
Please provide the entire call of the program
what do u mean?

**Comment by DaRealOctopus** [comment]
help @TheStrangePototo  @Lamaun

**Comment by Lamaun** [comment]
> Please provide the entire call of the program
> what do u mean?

Just copy everything in the terminal. All information a screenshot of the terminal would provide in textual form.

**Comment by DaRealOctopus** [comment]
how do u fix the audio not syncing with the video?

**Comment by DaRealOctopus** [comment]
@Lamaun sorry that I've not answered your question

**Comment by TheStrangePototo** [comment]
@DaRealOctopus You have to input the framerate of the video. You can check this by right clicking on the video file, clicking "Properties", and then clicking the "Details" tab.

**Comment by DaRealOctopus** [comment]
ok thx

**Comment by DaRealOctopus** [comment]
how to you get like the inhale-exhale parts?

**Comment by DaRealOctopus** [comment]
@TheStrangePototo

**Comment by DaRealOctopus** [comment]
nvm @TheStrangePototo

**Comment by DaRealOctopus** [comment]
sorry

**Comment by Lamaun** [comment]
> @Lamaun sorry that I've not answered your question

as long as it works for you now im happy

**Comment by Lamaun** [comment]
> how to you get like the inhale-exhale parts?

Just for documentation purposes
`python jumpcutter.py --input-file input.mp4 --silent_speed 1 --sounded_speed 999999`
will give you only the silent parts of the video. Inhale and exhale parts will probably be the loudest in that video. If you than throw the result into
`python jumpcutter.py --input-file input_ALTERED.mp4 --silent_speed 999999 --sounded_speed 1 --silent_threshold 0.02`
you will likely only get breathing. You might have to vary the silent_threshold for optimal results.
