### ISSUE TITLE
Frozen on frame halfway

### ISSUE THREAD

**Issue by TheStrangePototo** [carykh/jumpcutter#115]
The first video was fine, but on the 3 different videos I've tried it on afterwards have frozen on a frame halfway through the video or cutout video altogether.

**Comment by ThatOneCalculator** [comment]
Any logs?

**Comment by TheStrangePototo** [comment]
Like this?
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TheDomino.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-05-24T18:24:34.000000Z
  Duration: 00:15:52.74, start: 0.000000, bitrate: 916 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 785 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 00000187f222b900] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'TEMP/frame%06d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.27.103
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
      encoder         : Lavc58.53.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=28553 fps=203 q=3.0 Lsize=N/A time=00:15:52.71 bitrate=N/A speed=6.77x
video:1289104kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version N-94030-gcaabe1b495 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 53.100 / 58. 53.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TheDomino.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-05-24T18:24:34.000000Z
  Duration: 00:15:52.74, start: 0.000000, bitrate: 916 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 785 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'TEMP/audio.wav':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    ISFT            : Lavf58.27.103
    Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
      encoder         : Lavc58.53.100 pcm_s16le
size=  164124kB time=00:15:52.73 bitrate=1411.2kbits/s speed= 764x
video:0kB audio:164124kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000046%
20 time-altered frames saved.
40 time-altered frames saved.
60 time-altered frames saved.
80 time-altered frames saved.
100 time-altered frames saved.
120 time-altered frames saved.
140 time-altered frames saved.
160 time-altered frames saved.
180 time-altered frames saved.
200 time-altered frames saved.
220 time-altered frames saved.
240 time-altered frames saved.
260 time-altered frames saved.
280 time-altered frames saved.
300 time-altered frames saved.
320 time-altered frames saved.
340 time-altered frames saved.
360 time-altered frames saved.
380 time-altered frames saved.
400 time-altered frames saved.
420 time-altered frames saved.
440 time-altered frames saved.
460 time-altered frames saved.
480 time-altered frames saved.
500 time-altered frames saved.
520 time-altered frames saved.
540 time-altered frames saved.
560 time-altered frames saved.
580 time-altered frames saved.
600 time-altered frames saved.
620 time-altered frames saved.
640 time-altered frames saved.
660 time-altered frames saved.
680 time-altered frames saved.
700 time-altered frames saved.
720 time-altered frames saved.
740 time-altered frames saved.
760 time-altered frames saved.
780 time-altered frames saved.
800 time-altered frames saved.
820 time-altered frames saved.
840 time-altered frames saved.
860 time-altered frames saved.
880 time-altered frames saved.
900 time-altered frames saved.
920 time-altered frames saved.
940 time-altered frames saved.
960 time-altered frames saved.
980 time-altered frames saved.
1000 time-altered frames saved.
1020 time-altered frames saved.
1040 time-altered frames saved.
1060 time-altered frames saved.
1080 time-altered frames saved.
1100 time-altered frames saved.
1120 time-altered frames saved.
1140 time-altered frames saved.
1160 time-altered frames saved.
1180 time-altered frames saved.
1200 time-altered frames saved.
1220 time-altered frames saved.
1240 time-altered frames saved.
1260 time-altered frames saved.
1280 time-altered frames saved.
1300 time-altered frames saved.
1320 time-altered frames saved.
1340 time-altered frames saved.
1360 time-altered frames saved.
1380 time-altered frames saved.
1400 time-altered frames saved.
1420 time-altered frames saved.
1440 time-altered frames saved.
1460 time-altered frames saved.
1480 time-altered frames saved.
1500 time-altered frames saved.
1520 time-altered frames saved.
1540 time-altered frames saved.
1560 time-altered frames saved.
1580 time-altered frames saved.
1600 time-altered frames saved.
1620 time-altered frames saved.
1640 time-altered frames saved.
1660 time-altered frames saved.
1680 time-altered frames saved.
1700 time-altered frames saved.
1720 time-altered frames saved.
1740 time-altered frames saved.
1760 time-altered frames saved.
1780 time-altered frames saved.
1800 time-altered frames saved.
1820 time-altered frames saved.
1840 time-altered frames saved.
1860 time-altered frames saved.
1880 time-altered frames saved.
1900 time-altered frames saved.
1920 time-altered frames saved.
1940 time-altered frames saved.
1960 time-altered frames saved.
1980 time-altered frames saved.
2000 time-altered frames saved.
2020 time-altered frames saved.
2040 time-altered frames saved.
2060 time-altered frames saved.
2080 time-altered frames saved.
2100 time-altered frames saved.
2120 time-altered frames saved.
2140 time-altered frames saved.
2160 time-altered frames saved.
2180 time-altered frames saved.
2200 time-altered frames saved.
2220 time-altered frames saved.
2240 time-altered frames saved.
2260 time-altered frames saved.
2280 time-altered frames saved.
2300 time-altered frames saved.
2320 time-altered frames saved.
2340 time-altered frames saved.
2360 time-altered frames saved.
2380 time-altered frames saved.
2400 time-altered frames saved.
2420 time-altered frames saved.
2440 time-altered frames saved.
2460 time-altered frames saved.
ffmpeg version N-94030-gcaabe1b495 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 53.100 / 58. 53.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, image2, from 'TEMP/newFrame%06d.jpg':
  Duration: 00:00:49.56, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 50 tbn, 50 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, wav, from 'TEMP/audioNew.wav':
  Duration: 00:00:49.55, bitrate: 5644 kb/s
    Stream #1:0: Audio: pcm_f64le ([3][0][0][0] / 0x0003), 44100 Hz, stereo, dbl, 5644 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_f64le (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0000025737a8a880] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0000025737a8dd00] using SAR=1/1
[libx264 @ 0000025737a8dd00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000025737a8dd00] profile Progressive High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0000025737a8dd00] 264 - core 157 r2970 5493be8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'TheDomino_ALTERED.mp4':
  Metadata:
    encoder         : Lavf58.27.103
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 50 fps, 12800 tbn, 50 tbc
    Metadata:
      encoder         : Lavc58.53.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.53.100 aac
frame= 2478 fps=166 q=-1.0 Lsize=    3776kB time=00:00:49.55 bitrate= 624.2kbits/s speed=3.32x
video:2972kB audio:741kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.697832%
[libx264 @ 0000025737a8dd00] frame I:25    Avg QP:17.21  size: 17071
[libx264 @ 0000025737a8dd00] frame P:681   Avg QP:14.44  size:  2476
[libx264 @ 0000025737a8dd00] frame B:1772  Avg QP:17.05  size:   524
[libx264 @ 0000025737a8dd00] consecutive B-frames:  3.3%  2.9%  3.4% 90.4%
[libx264 @ 0000025737a8dd00] mb I  I16..4: 46.1% 48.8%  5.0%
[libx264 @ 0000025737a8dd00] mb P  I16..4:  1.8%  4.1%  0.4%  P16..4:  4.9%  1.3%  0.4%  0.0%  0.0%    skip:87.2%
[libx264 @ 0000025737a8dd00] mb B  I16..4:  0.5%  0.5%  0.0%  B16..8:  3.0%  0.5%  0.1%  direct: 0.2%  skip:95.4%  L0:46.8% L1:48.7% BI: 4.5%
[libx264 @ 0000025737a8dd00] 8x8 transform intra:57.1% inter:77.3%
[libx264 @ 0000025737a8dd00] coded y,uvDC,uvAC intra: 30.3% 25.5% 2.2% inter: 1.0% 0.6% 0.0%
[libx264 @ 0000025737a8dd00] i16 v,h,dc,p: 61% 21%  9% 10%
[libx264 @ 0000025737a8dd00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 22% 30%  2%  2%  3%  3%  2%  3%
[libx264 @ 0000025737a8dd00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 25% 14%  4%  6%  6%  6%  5%  4%
[libx264 @ 0000025737a8dd00] i8c dc,h,v,p: 69% 14% 15%  2%
[libx264 @ 0000025737a8dd00] Weighted P-Frames: Y:7.9% UV:5.0%
[libx264 @ 0000025737a8dd00] ref P L0: 65.8% 23.9%  7.8%  2.4%  0.2%
[libx264 @ 0000025737a8dd00] ref B L0: 90.3%  8.3%  1.4%
[libx264 @ 0000025737a8dd00] ref B L1: 98.3%  1.7%
[libx264 @ 0000025737a8dd00] kb/s:491.12
[aac @ 0000025737aaf280] Qavg: 6402.965

**Comment by TheStrangePototo** [comment]
@ThatOneCalculator Like this?
I forgot to @ you the first time, that's why it's so late.

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TheDomino.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-05-24T18:24:34.000000Z
  Duration: 00:15:52.74, start: 0.000000, bitrate: 916 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 785 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 00000187f222b900] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'TEMP/frame%06d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.27.103
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
      encoder         : Lavc58.53.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=28553 fps=203 q=3.0 Lsize=N/A time=00:15:52.71 bitrate=N/A speed=6.77x
video:1289104kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version N-94030-gcaabe1b495 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 53.100 / 58. 53.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TheDomino.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-05-24T18:24:34.000000Z
  Duration: 00:15:52.74, start: 0.000000, bitrate: 916 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 785 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'TEMP/audio.wav':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    ISFT            : Lavf58.27.103
    Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s (default)
    Metadata:
      creation_time   : 2018-05-24T18:24:34.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/24/2018.
      encoder         : Lavc58.53.100 pcm_s16le
size=  164124kB time=00:15:52.73 bitrate=1411.2kbits/s speed= 764x
video:0kB audio:164124kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000046%
20 time-altered frames saved.
40 time-altered frames saved.
60 time-altered frames saved.
80 time-altered frames saved.
100 time-altered frames saved.
120 time-altered frames saved.
140 time-altered frames saved.
160 time-altered frames saved.
180 time-altered frames saved.
200 time-altered frames saved.
220 time-altered frames saved.
240 time-altered frames saved.
260 time-altered frames saved.
280 time-altered frames saved.
300 time-altered frames saved.
320 time-altered frames saved.
340 time-altered frames saved.
360 time-altered frames saved.
380 time-altered frames saved.
400 time-altered frames saved.
420 time-altered frames saved.
440 time-altered frames saved.
460 time-altered frames saved.
480 time-altered frames saved.
500 time-altered frames saved.
520 time-altered frames saved.
540 time-altered frames saved.
560 time-altered frames saved.
580 time-altered frames saved.
600 time-altered frames saved.
620 time-altered frames saved.
640 time-altered frames saved.
660 time-altered frames saved.
680 time-altered frames saved.
700 time-altered frames saved.
720 time-altered frames saved.
740 time-altered frames saved.
760 time-altered frames saved.
780 time-altered frames saved.
800 time-altered frames saved.
820 time-altered frames saved.
840 time-altered frames saved.
860 time-altered frames saved.
880 time-altered frames saved.
900 time-altered frames saved.
920 time-altered frames saved.
940 time-altered frames saved.
960 time-altered frames saved.
980 time-altered frames saved.
1000 time-altered frames saved.
1020 time-altered frames saved.
1040 time-altered frames saved.
1060 time-altered frames saved.
1080 time-altered frames saved.
1100 time-altered frames saved.
1120 time-altered frames saved.
1140 time-altered frames saved.
1160 time-altered frames saved.
1180 time-altered frames saved.
1200 time-altered frames saved.
1220 time-altered frames saved.
1240 time-altered frames saved.
1260 time-altered frames saved.
1280 time-altered frames saved.
1300 time-altered frames saved.
1320 time-altered frames saved.
1340 time-altered frames saved.
1360 time-altered frames saved.
1380 time-altered frames saved.
1400 time-altered frames saved.
1420 time-altered frames saved.
1440 time-altered frames saved.
1460 time-altered frames saved.
1480 time-altered frames saved.
1500 time-altered frames saved.
1520 time-altered frames saved.
1540 time-altered frames saved.
1560 time-altered frames saved.
1580 time-altered frames saved.
1600 time-altered frames saved.
1620 time-altered frames saved.
1640 time-altered frames saved.
1660 time-altered frames saved.
1680 time-altered frames saved.
1700 time-altered frames saved.
1720 time-altered frames saved.
1740 time-altered frames saved.
1760 time-altered frames saved.
1780 time-altered frames saved.
1800 time-altered frames saved.
1820 time-altered frames saved.
1840 time-altered frames saved.
1860 time-altered frames saved.
1880 time-altered frames saved.
1900 time-altered frames saved.
1920 time-altered frames saved.
1940 time-altered frames saved.
1960 time-altered frames saved.
1980 time-altered frames saved.
2000 time-altered frames saved.
2020 time-altered frames saved.
2040 time-altered frames saved.
2060 time-altered frames saved.
2080 time-altered frames saved.
2100 time-altered frames saved.
2120 time-altered frames saved.
2140 time-altered frames saved.
2160 time-altered frames saved.
2180 time-altered frames saved.
2200 time-altered frames saved.
2220 time-altered frames saved.
2240 time-altered frames saved.
2260 time-altered frames saved.
2280 time-altered frames saved.
2300 time-altered frames saved.
2320 time-altered frames saved.
2340 time-altered frames saved.
2360 time-altered frames saved.
2380 time-altered frames saved.
2400 time-altered frames saved.
2420 time-altered frames saved.
2440 time-altered frames saved.
2460 time-altered frames saved.
ffmpeg version N-94030-gcaabe1b495 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 53.100 / 58. 53.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, image2, from 'TEMP/newFrame%06d.jpg':
  Duration: 00:00:49.56, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 50 tbn, 50 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, wav, from 'TEMP/audioNew.wav':
  Duration: 00:00:49.55, bitrate: 5644 kb/s
    Stream #1:0: Audio: pcm_f64le ([3][0][0][0] / 0x0003), 44100 Hz, stereo, dbl, 5644 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_f64le (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0000025737a8a880] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0000025737a8dd00] using SAR=1/1
[libx264 @ 0000025737a8dd00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000025737a8dd00] profile Progressive High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0000025737a8dd00] 264 - core 157 r2970 5493be8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'TheDomino_ALTERED.mp4':
  Metadata:
    encoder         : Lavf58.27.103
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 50 fps, 12800 tbn, 50 tbc
    Metadata:
      encoder         : Lavc58.53.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.53.100 aac
frame= 2478 fps=166 q=-1.0 Lsize=    3776kB time=00:00:49.55 bitrate= 624.2kbits/s speed=3.32x
video:2972kB audio:741kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.697832%
[libx264 @ 0000025737a8dd00] frame I:25    Avg QP:17.21  size: 17071
[libx264 @ 0000025737a8dd00] frame P:681   Avg QP:14.44  size:  2476
[libx264 @ 0000025737a8dd00] frame B:1772  Avg QP:17.05  size:   524
[libx264 @ 0000025737a8dd00] consecutive B-frames:  3.3%  2.9%  3.4% 90.4%
[libx264 @ 0000025737a8dd00] mb I  I16..4: 46.1% 48.8%  5.0%
[libx264 @ 0000025737a8dd00] mb P  I16..4:  1.8%  4.1%  0.4%  P16..4:  4.9%  1.3%  0.4%  0.0%  0.0%    skip:87.2%
[libx264 @ 0000025737a8dd00] mb B  I16..4:  0.5%  0.5%  0.0%  B16..8:  3.0%  0.5%  0.1%  direct: 0.2%  skip:95.4%  L0:46.8% L1:48.7% BI: 4.5%
[libx264 @ 0000025737a8dd00] 8x8 transform intra:57.1% inter:77.3%
[libx264 @ 0000025737a8dd00] coded y,uvDC,uvAC intra: 30.3% 25.5% 2.2% inter: 1.0% 0.6% 0.0%
[libx264 @ 0000025737a8dd00] i16 v,h,dc,p: 61% 21%  9% 10%
[libx264 @ 0000025737a8dd00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 22% 30%  2%  2%  3%  3%  2%  3%
[libx264 @ 0000025737a8dd00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 25% 14%  4%  6%  6%  6%  5%  4%
[libx264 @ 0000025737a8dd00] i8c dc,h,v,p: 69% 14% 15%  2%
[libx264 @ 0000025737a8dd00] Weighted P-Frames: Y:7.9% UV:5.0%
[libx264 @ 0000025737a8dd00] ref P L0: 65.8% 23.9%  7.8%  2.4%  0.2%
[libx264 @ 0000025737a8dd00] ref B L0: 90.3%  8.3%  1.4%
[libx264 @ 0000025737a8dd00] ref B L1: 98.3%  1.7%
[libx264 @ 0000025737a8dd00] kb/s:491.12
[aac @ 0000025737aaf280] Qavg: 6402.965

**Comment by TheStrangePototo** [comment]
@ThatOneCalculator  wait im an idiot i put in the wrong framerate

**Comment by Lamaun** [comment]
I would like to add, that there are forks & [pull requests](https://github.com/carykh/jumpcutter/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+framerate) of this project which are able to detect the framerate (in most cases)

Seems like @carykh just couldn't find the time to review them.

**Comment by TheStrangePototo** [comment]
@Lamaun It's no problem, videos show their framerates when you look at the details in Properties.
