### ISSUE TITLE
how to run on mac after librarys installed

### ISSUE THREAD

**Issue by NalinPlad** [carykh/jumpcutter#130]

**Comment by NalinPlad** [comment]
I installed and libraries and I opened jumpcutter.py in terminal but it doesn't seem to work.

**Comment by jsrobson10** [comment]
You need to be more specific: What error messages is it giving? What python version are you using? Are you using python 3?

**Comment by JamesGelok** [comment]
@NalinPlad 
I'm a mac user on Catalina. I'm gonna give my best guess at what went wrong by writing out what I did.
> I installed and libraries and I opened jumpcutter.py in terminal but it doesn't seem to work.

After making sure I was using the `pip3` command for installs and the `python3` command for running it, I needed to install ffmpeg. (PIL aka [pillow](https://github.com/pytorch/pytorch/issues/3825#issuecomment-346254569) was weird in that the library name and install weren't the same. modify the command to use pip3 if u need)

If you have [homebrew](https://brew.sh/), you can type
```bash
brew install ffmpeg
```

then while you're in the directory, run it on your video file using the command

```
python3 jumpcutter.py --input_file YourVideoFileLocatedInTheSameDirectory.mp4
```
 it should run UNLESS you have a TEMP directory in that folder from a previous attempt. 
Then you need to delete that and try again. Goodluck.

**Comment by JacksonChen666** [comment]
If you need to, adjust the frame rate to something else if the videos go out of sync
