### ISSUE TITLE
this message comes after the time altered frames thing

### ISSUE THREAD

**Issue by BlockListed** [carykh/jumpcutter#138]
Traceback (most recent call last):
  File "jumpcutter.py", line 166, in <module>
    outputAudioData = np.concatenate((outputAudioData,alteredAudioData/maxAudioVolume))
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (21416448, 2) and data type float64

how would i fix this?

**Comment by Lamaun** [comment]
Seems like you have a very long video. Try splitting it and feed the parts into jumpcutter.
