### ISSUE TITLE
ffmpeg?

### ISSUE THREAD

**Issue by CtrlAlt-Delete** [carykh/jumpcutter#142]
I get an error saying this when running the program
"/bin/sh: 1: ffmpeg: not found
/bin/sh: 1: ffmpeg: not found
Traceback (most recent call last):
  File "Test.py", line 108, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "/home/*MY_NAME*/.local/lib/python3.6/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'"

Is it a problem with ffmpeg or some other thing? Not really sure how to solve this issue. Thanks for any help!

**Comment by Lamaun** [comment]
Have you installed ffmpeg? `apt install ffmpeg`
And it seems like you also did not do `pip install -r requirements.txt`

**Comment by Lamaun** [comment]
I have just added some more documentation for installing and usage here:
https://github.com/Lamaun/jumpcutter/blob/master/README.md
Maybe that also helps you

**Comment by CtrlAlt-Delete** [comment]
Yes thank you, I was positive I had ffmpeg but apparently I had removed it or something... such a stupid mistake on my side.  But that updated readme.txt does help! Thank you and sorry for taking your time on this simple problem

**Comment by rougetimelord** [comment]
Hey, little reminder to close your issue.

**Comment by CtrlAlt-Delete** [comment]
Sorry! First time using GitHub like this. It's closed now
