### ISSUE TITLE
This app cant run on your pc - access denied

### ISSUE THREAD

**Issue by Harp3rDev** [carykh/jumpcutter#153]
I am running windows 10, I have installed all of the requirements, am in the jumpcutter folder, then ran the program with this command C:\Users\myname\AppData\Local\Programs\Python\Python37\python.exe jumpcutter.py --input_file homework.mp4. A windows popup says. "This app can't run on your pc." Then cmd says access denied. I am also running cmd as admin. 
![image](https://user-images.githubusercontent.com/51060508/73891779-fe513e00-4842-11ea-90c2-582453e97171.png)

**Comment by Lamaun** [comment]
Weird error...

Just to make sure: Did you run `C:\Users\Harpe\AppData\Local\Programs\Python\Python37\python.exe -m pip install -r requirements.txt` and just didn't include it in the screenshot?

However the message shouldn't be `Access is denied.` if that was the problem. Another difference to my setup is that you used your OneDrive (maybe try it in another location?)
If that also doesn't help, it is most likely some problem with your system. Search for 
"This app cant run on your pc" and you will find some guides. 

Also jumpcutter doesn't need admin permissions.

**Comment by Harp3rDev** [comment]
I searched and checked my python folder, for some reason python was 0kb so i reinstalled it. I forgot to close the issue.
