### ISSUE TITLE
i'm dumb dumb; any idea how to work this out 

### ISSUE THREAD

**Issue by Toflamo** [carykh/jumpcutter#175]
Hi first, thanks in advance

So, I don't have any experience with coding, python or any similar to understand what is that I'm doing wrong and the thing is that, I really want this Automatic editing tool since it will be and immense improve in the time when I'm editing videos.

I don't know how to use the Powershell but this is where I am. 
I follow the steps attached below until the last one, where my problem is. I think i am so close to making this that this may seem stupid even.

Thanks again. 
/
/
/
_Picture 1. The steps mentioned above.
Picture 2. The problem the Powershell is telling me._

![Anotación 2020-04-29 224429](https://user-images.githubusercontent.com/64557807/80645973-2def9b00-8a6c-11ea-9268-a5667f567bd6.jpg)

![Anotación 2020-04-29 225601](https://user-images.githubusercontent.com/64557807/80646225-a48c9880-8a6c-11ea-935e-6d8c9100f89b.jpg)

pd: the video in matter, **"hola.mp4"** and the jumpcutter.py are in the same folder as the python.exe _(C:\Users\Dario\AppData\Local\Programs\Python\Python37)_ since I didn't know how to refer to it if it wasn't in the same folder.

pd2: i saw carykh commenting about creating a .exe to make this easier to non-coding people like me; any news in that respect?  

/

**Comment by WyattBlue** [comment]
python **the language** does not have cary's program
can you tell what **exactly** you downloaded and where did you put it.

**Comment by shanlemon** [comment]
try doing "pip install pytube3"

**Comment by zPaw** [comment]
> try doing "pip install pytube3"

If `pip install pytube3` doesn't work, you can also try `python.exe -m pip install pytube3`.

**Comment by Toflamo** [comment]
**_Everything is working fine now! Thanks a lot for the help :)_**

I'll be replying to the issues I had here to make easier finding a solution for some non-tech people with the same problems as me. 

- _@WyattBlue_ I installed **Python 3.7.3** and then put the _.py_ file from carykh _(jumpcutter.py)_ in the same folder as the Python.exe, as you can see in the picture below. 
Then, I downloaded the ffmpeg's files from[ here ](https://github.com/lamaun/jumpcutter/#windows)and put the ffmpeg.exe in the jumpcutter master's folder. After this, I had the issues remarked above. Now, this issues are solved.

- @shanlemon @zPaw This is where my solution was. After trying `pip install pytube3` and `python.exe -m pip install pytube3` the problem was fixed, in nearly a second. I tried the same video as before **"hola.mp4"**, and it worked. That's it! 
However, a new problem happened where some **TEMP folder** in the python directory _(C:\Users\Dario\AppData\Local\Programs\Python\Python37\TEMP)_ appeared,  and, after this first test I couldn't test again. I don't have a screenshot, but in the Powershell was a message in the lines of **_Cannot create a file when that file already exists 'TEMP' winerror183_**. So, by common sense, I understood that deleting this folder was going to make the code work again. And it worked again.

/
/
/
_Picture. Where I put the jumpcutter.py and the ffmpeg.exe to work._
![Anotación 2020-04-30 125152](https://user-images.githubusercontent.com/64557807/80702613-a6447380-8ae1-11ea-834c-440f8d88b528.jpg)
_At this point I've made five more test and everything runs smoothly. Thx again.
I hope this threat may be helpful ;)_

/
