### ISSUE TITLE
jumpcutter is dead, here's what you can do.

### ISSUE THREAD

**Issue by WyattBlue** [carykh/jumpcutter#180]
jumpcutter is dead. Cary is never going to update this repo and any bugs you have and features you want will never get resolved. 

Instead, try out a different program made by someone else. They fix much of the bugs and some even have new features. 

Sadly, most of the projects are buried, so it's difficult finding a program that's right for you so I made a guide for the projects that improve upon jumpcutter.

**EDIT: added Cut The Crap and some extra info**

| Features | Jumpcutter  | [Auto-Editor](https://github.com/WyattBlue/auto-editor) | [Lamaun's fork](https://github.com/Lamaun/jumpcutter) | [Cut The Crap](https://github.com/jappeace/cut-the-crap)
|-|-|-|-|-|
|can set sounded speed|✅|✅|✅|❌|❌
|can download YT links|✅|✅|✅|❌|❌
|supports negative frame margin|❌|❌|✅|❌
|low memory usage|❌|✅|✅|❌|❌|
|runs really fast|❌|✅|❌|✅|
|detect based on motion|❌|✅|❌|❌|
|works on audio files|❌|✅|✅|❌|
|support for vids with multiple audio tracks|❌|✅|❌|✅|
|cut by a certain track|❌|✅|❌|✅|

**Other stuff**

|| Jumpcutter  | [Auto-Editor](https://github.com/WyattBlue/auto-editor) | [Lamaun's fork](https://github.com/Lamaun/jumpcutter) | [Cut The Crap](https://github.com/jappeace/cut-the-crap)
|-|-|-|-|-|
|supported OSes|windows, linux| windows, macOS, linux| windows, macOS, linux| macOS, linux|
|language|python (🐍)|🐍|🐍|haskel|
|install packages (if any)|nix|pip|nix, docker|nix, .deb|

You can immediately install auto-editor by running this:

```terminal
pip3 install auto-editor
```

If you can find another good project, please tell me.

**Comment by m-rey** [comment]
You can look for more active projects/forks on this list:

https://techgaun.github.io/active-forks/index.html#carykh/jumpcutter

**Comment by davidoskky** [comment]
I originally wrote a PR to support audio files.
If you are trying to work on audio only, with no video I do not recommend using this software (or any of its forks).
You should try out the program sox, which has more configurations and runs much faster.

**Comment by jappeace** [comment]
also checkout my reimplementation: https://github.com/jappeace/cut-the-crap,

I even packaged for debian and nixos. I'm in the final stages of making speech recognition work, allowing the cutting of background noise (checkout the speech branch).
After I finish that i'll make a frontend so ordinary people can use it.
Everything opensource.

Please help me if you're interested in this project (and or interested in haskell), I'd be happy to help anyone work on any issue.

**Comment by gayuha** [comment]
Is there something similar in a form of a plugin for VLC or something, that can speed up quiet parts of a video on the fly? Decoding the jpg's and re-encoding takes a lot of time.

**Comment by johan456789** [comment]
@gayuha There's [skip-silence](https://github.com/vantezzen/skip-silence) that works as a browser extension.

**Comment by WofWca** [comment]
Another browser extension: https://chrome.google.com/webstore/detail/jump-cutter/lmppdpldfpfdlipofacekcfleacbbncp

**Comment by DonaldTsang** [comment]
Other considered features: 
Blipper cutting https://github.com/carykh/jumpcutter/issues/121
Speech removal https://github.com/carykh/jumpcutter/issues/122
Gesture cutting (as promised) https://github.com/carykh/jumpcutter/issues/123

**Comment by jurf** [comment]
@gayuha I tried it a year ago, couldn’t get it to work. I don’t remember the details, I remember VLC dropped support for some callbacks needed to make it function. Feel free to try again.

**Comment by Tremeschin** [comment]
I'll be implementing own "version", algorithm implementation of this on my [MMV project](https://github.com/Tremeschin/modular-music-visualizer) as a bonus (yea it's becomming somewhat of a video editor with some extensions) as I already have everything kinda ready and we on online classes world now, been wanting to code it anyways.

Will be able to not only visualize real time but render quite fast if I can get my audio processing right.

Also thanks for the idea of `detect based on motion` this should be easy by calculating MSE between two frames with some resolution biasing, will also put two scalars for how fast it grows the audio when there is some, how fast to decay individually and interpolated. Feels totally doable. Talk to you guys in a few days hopefully.

**Comment by Tremeschin** [comment]
Hey I have just commited basic jumpcutter-like functionality, you can check them [here](https://github.com/Tremeschin/modular-music-visualizer#extra-modes). It's not the most tested and accurate thing nor syncs very well yet for low audio batch sizes or high speeds, but it's at least something :welp: wahoo

I'm confident it'll eventually get better over time.. btw writing the syncing functions was hard maaan, took like 6 to 8 hours in total until I found that change of perspective which solves almost all problems.

I haven't tested the other projects listed on the original issue to check how fast is _"runs really fast"_, I can improve mine by doing audio processing plus final video render at the same time instead of linear for now but it's at least realtime+ fast mine considering 30fps videos or so, but that's a thing for later on.

**Comment by carykh** [comment]
I have good news! My friends and I have been working on a polished version of jumpcutter here: https://jumpcutter.com/

Also, I would prefer you avoid this sort of call-out language. Please watch this video for why I think it's harmful to claim YouTubers who post code publicly are "killing their projects" by not maintaining them ad infinitum, a standard that almost every other YouTuber (vloggers, gamers, beauty gurus, etc.) are never held up to.

https://www.youtube.com/watch?v=7YBY4yLfw4g&t=2m21s

**Comment by m-rey** [comment]
> My friends and I have been working on a polished version of jumpcutter

Any plans to release an open source "community version" of it?

**Comment by Dreiparrent** [comment]
@m-rey we have our new render code open source https://github.com/JumpCutter/JC-render and our JumpCutter algorithm is just a JS update to the @carykh original. We are looking forward to cli and more open code, but we are a small team. We are working with Cary and we'd love to work with the community too https://discord.gg/NQbbCFvY
