### ISSUE TITLE
[todo] Graphical User Interface

### ISSUE THREAD

**Issue by ascpixi** [carykh/jumpcutter#33]
### I suggest making the GUI in pyQt4, or Tkinter.

The GUI was first mentioned **in this issue**:
#3 [Executable file](https://github.com/carykh/jumpcutter/issues/3)

**Comment by elff1493** [comment]
i have actual made a basic one but i do not know how to use git so you can see it when i figure out how git works

**Comment by abhiTronix** [comment]
> i have actual made a basic one but i do not know how to use git so you can see it when i figure out how git works

@elff1493 , follow these commands:

```
fork this repo.
clone the forked repo.
cd <to the folder you want to commit> 
git add .
git commit -m "Message to commit"
git push
```
then start the pull-request on your git. Hope it helps.

**Comment by elff1493** [comment]
"Push rejected: Push master to origin/master was rejected by remote"

**Comment by abhiTronix** [comment]
@elff1493 Did you first forked this repo.?

**Comment by elff1493** [comment]
i think my email is making problems

**Comment by abhiTronix** [comment]
@elff1493 Check this https://stackoverflow.com/questions/52013203/first-git-push-rejected

**Comment by elff1493** [comment]
fixed the problem, was my email

**Comment by elff1493** [comment]
[someone else](https://github.com/carykh/jumpcutter/pull/35) made a GUI before i got my git working, check them out its neet

**Comment by A0A3R2E6** [comment]
Hello, I made one on Qt Designer.
