### ISSUE TITLE
Need help for win10

### ISSUE THREAD

**Issue by Puppy288** [carykh/jumpcutter#45]
Am i dumb? I seriously cant figure out how to make it work on windows 10. command prompt keeps saying python isnt a command. (I'm typing 'python jumpcutter.py -h')

**Comment by JettJamez** [comment]
Same here! I'm very confused.

**Comment by Kingeng** [comment]
@Puppy288 
do you add python.exe to windows PATH ?
if not , search for Environment Variable or google it

**Comment by Puppy288** [comment]
> 
> 
> @Puppy288
> do you add python.exe to windows PATH ?

wait how do you do that?

**Comment by DeflatedPickle** [comment]
@Puppy288, when installing Python with the GUI installer, there's a checkbox you can click that'll add it to your `PATH` for you. You can either re-install it and do that, or you can find the installed location and add it to your `PATH` yourself.

I find that the quickest/easiest way is to search in the taskbar search bar "IDLE" then right-click on that, click "Open file location" in the menu, then right-click on the selected item in the file explorer and click "Open file location" on that, and then you're at the installed folder. You can then take that path, plus "`/python.exe`" and add that to your `PATH`.

**Comment by Puppy288** [comment]
@DeflatedPickle i needed to update python anyways so thank you
