### ISSUE TITLE
How to run on Mac

### ISSUE THREAD

**Issue by joelpisme** [carykh/jumpcutter#51]
Does anyone know how to run this on terminal on Mac? 

Also, how do I install Pillow, audiotsm, scipy, numpy and pytube?

What is the nix-build and how do I use it?

**Comment by izedout** [comment]
Its all via python.

First install python 3.6
Then run pip install pillow 
Pip install audiotsm 
Etc

Run it the same way as shown in the video

**Comment by izedout** [comment]
You must also install ffmpeg. I don't have a Mac so it's best to google the installation process for that

**Comment by dotcomboom** [comment]
You can just install ffmpeg through Homebrew: `brew install ffmpeg`

**Comment by joelpisme** [comment]
Thanks so much everyone. Got everything downloaded
