### ISSUE TITLE
Syntax Error and No such file or directory: 'TEMP/audio.wav'

### ISSUE THREAD

**Issue by joelpisme** [carykh/jumpcutter#58]
Hello, when I run the code I have these error messages pop up:

/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `ffmpeg -i video.MOV -qscale:v 3 TEMP/frame%06d.jpg -hide_banner'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `ffmpeg -i video.MOV -ab 160k -ac 2 -ar 44100 -vn TEMP/audio.wav'
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/io/wavfile.py", line 151, in read
    fid = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'TEMP/audio.wav'

**Comment by cGev69** [comment]
Hey how did you fix that issue?

**Comment by ThatOneCalculator** [comment]
Oh it's because that video was probably encoded wrong. The initial algorithm carykh used was a bit jank. Check my profile for rewritten version that fixed that issue

**Comment by cGev69** [comment]
the issue was fixed by installing ffmpeg

**Comment by ThatOneCalculator** [comment]
Oh I still got that issue AFTER installing ffmpeg

**Comment by ThatOneCalculator** [comment]
It's because -c doesn't cover .avi files encoded in h.265
