### ISSUE TITLE
[Error] No such file or directory: 'TEMP/audio.wav'

### ISSUE THREAD

**Issue by Micrograx** [carykh/jumpcutter#8]
Was playing with this but getting an error every time:

```
/bin/sh: ffmpeg: command not found
/bin/sh: ffmpeg: command not found
Traceback (most recent call last):
  File "jumpcutter.py", line 93, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "/usr/local/lib/python3.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
```

The TEMP folder is created but left there. Any idea what could be wrong?

Running it in Mac OS 10.14, with all the libraries installed. Tried python 2 and 3, no changes. My file is a .MOV captured from an iPhone.

**Comment by MisterX2000** [comment]
You haven't installed ffmpeg

`/bin/sh: ffmpeg: command not found`

You can get it from here (just download and unzip in the folder or install it globally):
http://ffmpeg.org/download.html

**Comment by Rosaroterpanther** [comment]
You can use brew
`brew install ffmpeg`

**Comment by Micrograx** [comment]
Great. Thanks. All working now.
