### ISSUE TITLE
ImportError: No module named audiotsm

### ISSUE THREAD

**Issue by MBear227** [carykh/jumpcutter#89]
I tried jumpcutter.py but I got this:
`$ python jumpcutter.py -h
Traceback (most recent call last):
  File "jumpcutter.py", line 4, in <module>
    from audiotsmv import phasevocoder
ImportError: No module named audiotsm`
I swear I installed audiotsm, and it should have been fine (`pip install audiotsm`) so why can't Python find it? I'm kind of a noob to Python. Some help, please?

**Comment by Kingeng** [comment]
maybe you install that on another environment variable and run the code by some thing else
check that by `which python` then run python (previous command output) and try `import audiotsmv`

**Comment by Luctins** [comment]
you're suposed to use this with `python3` and (install it with `pip3`)

**Comment by Mallington** [comment]
You need to make sure all of the following packages are installed:
Pillow
audiotsm
scipy
numpy
pytube

To install them, simply use the command: `pip3 install <put package name here>`

**Comment by MBear227** [comment]
nvm I am now using the exe version by Jabrils (https://github.com/Jabrils/jumpcutter) and it works fine, I didn't have this problem.

**Comment by puccj** [comment]
Same problem here but even weirder: yesterday everything worked fine and I successfull converted a video. Today I got the "No module named audiotsm" error. I tried uninstall and install again the module, but nothing happen

**Comment by akshaykhanna** [comment]
Getting the same problem, tried reinstalling all these modules

> Pillow
> audiotsm
> scipy
> numpy
> pytube
