### ISSUE TITLE
No clear install instructions

### ISSUE THREAD

**Issue by Steveycat** [carykh/jumpcutter#93]
I'm looking to use this tool to help speed up simple let's plays videos that normally take a long time to edit when all I'm doing is removing silent periods. I would love to use this tool but I am having a hard time getting it to work. Please in the read me file (or another clearly marked file) can you leave install instructions on how to set this up
Thanks :D

p.s: I'm on Windows 10 if anyone can help me figure out what I need to do :)

**Comment by SHIuSH** [comment]
install python from the official site.(check the OS and 
using cmd locate the jumpcutter folder and run the command
pip install -r requirements.txt
enjoy using the thing

**Comment by Steveycat** [comment]
I have followed the steps you have stated above put when I try to run the jumpcitter,py file, cmd flashes up and then disappears again. Is there a specific way to start the program or a step I may have missed? (This is my first time working with python files)

**Comment by SHIuSH** [comment]
you don't run the .py file. You open a command prompt/powershell, locate the jumpcutter-master folder on your drive(with cmd basic navigation commands) and run a command like carykh did in his video.

**Comment by JOWEdumb** [comment]
I tried on windows 10 too and it didn't work

**Comment by SHIuSH** [comment]
> I tried on windows 10 too and it didn't work

you're on github, (on the internet for that matter) the reply "it didn't work" doesn't say anything. Be specific and don't expect people to read your mind from across the world

**Comment by ThatOneCalculator** [comment]
... Have you ever used python before?

**Comment by Aaronlikesmath** [comment]
> I'm looking to use this tool to help speed up simple let's plays videos that normally take a long time to edit when all I'm doing is removing silent periods. I would love to use this tool but I am having a hard time getting it to work. Please in the read me file (or another clearly marked file) can you leave install instructions on how to set this up
> Thanks :D
> 
> p.s: I'm on Windows 10 if anyone can help me figure out what I need to do :)
made this if that helps you just run the scripts
https://github.com/Aaronlikesmath/Easy-Carykh-jumpcutter/releases/tag/V1.0
